import { ContainerProps } from "./container.types";
export declare const Container: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const FlexContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const ColumnContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const RowContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const GridContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const CenterAlignedColumnContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const FlexStartCenterAlignedColumnContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const FlexStartColumnContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
export declare const OverflowFlexStartCenterAlignedColumnContainer: import("styled-components").StyledComponent<"div", import("styled-components").DefaultTheme, ContainerProps, never>;
